# Generated by Django 5.2.17 on 2026-08-22 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_goal_user_status_idx_and_more'),
        ('studies', '0001_initial'),
        ('tasks', '0002_task_task_user_status_idx_task_task_user_goal_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'started_at'], name='study_user_started_at_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'goal'], name='study_user_goal_idx'),
        ),
    ]
