# Generated by Django 5.2.17 on 2026-08-22 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goal_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'priority'], name='goal_user_priority_idx'),
        ),
    ]
