# Generated by Django 5.2.17 on 2026-08-22 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['resource', 'chunk_index'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_document_user_id_e7b386_idx'), models.Index(fields=['resource', 'chunk_index'], name='ai_document_resourc_ee4a33_idx')],
                'constraints': [models.UniqueConstraint(fields=('resource', 'chunk_index'), name='unique_resource_chunk_index')],
            },
        ),
    ]
