# Generated by Django 5.2.17 on 2026-08-22 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_goal_user_status_idx_and_more'),
        ('resources', '0001_initial'),
        ('tasks', '0002_task_task_user_status_idx_task_task_user_goal_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['user', 'created_at'], name='resource_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['user', 'goal'], name='resource_user_goal_idx'),
        ),
    ]
